### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by tanelj** [Voog/design-paris#1]
Bugs:
- [x] blog comment on-page delete button is missing
- [x] Article and article dates are not localized https://github.com/Edicy/design-paris/blob/paris-v2/layouts/blog_article.tpl#L35
- [x] Style for form success message is missing (`class="form_notice"`)
- [x] Article layout uses `page.data` - should use `article.data` https://github.com/kaspar-naaber/design-paris/blob/master/https://github.com/Edicy/design-paris/blob/paris-v2/layouts/blog_article.tpl#L9
- [x] Mobile menu should begin right after the "burger"
- [x] Front page: In mobile view article thumbs are going to early to on column
- [x] Comment form description auto grow is now working
- [x] Comment form labels are miss placed in wider mobile view
- [x] In edit mode there are to few space between gallery area is next to text area when gallery is next to text area (ok in preview mode)
- [x] FB admin example should not be shown when the value is missing ( https://github.com/Edicy/design-paris/blob/paris-v2/components/html-head.tpl#L22
- [x] Search is missing in mobile view
- [x] Search placeholder is missing
- [x] There is no space between blog article body and tags in article edit view.
- [x] Blog thumb titles is shown on Search results popup:

![paris-search-results](https://cloud.githubusercontent.com/assets/378755/3431814/116d4b14-006e-11e4-8061-cd41cad31018.png)
